# File: .github/workflows/workflow.yml
# made repo public 
name: Workflow 1

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  
  build-and-deploy:
    
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az group create --location westus --name ${{ vars.resource_group_name }}
          az storage account create --name ${{ vars.storage_account_name }} --resource-group ${{ vars.resource_group_name }} --location westus --sku Standard_LRS
          az storage container create --name ${{ vars.container_name }} --account-name ${{ vars.storage_account_name }}
          az storage account keys list -g ${{ vars.resource_group_name }} -n ${{ vars.storage_account_name }}

          
